language: ruby
os:
- linux
dist: jammy
cache:
  directories:
  - "/home/travis/.rvm/"
  - "$TRAVIS_BUILD_DIR/webpack/node_modules"
  - "$TRAVIS_BUILD_DIR/public/bundled"
  bundler: true
  yarn: true
group: previous
before_script:
- wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
- sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
- sudo apt-get update -q
- sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew
  mysql-server
- sudo systemctl restart mysql
- sudo mysql_upgrade
- mysql --version
- echo mysql --version
services:
- mysql
addons:
  firefox: '80.0'
install:
- nvm install v16.14.2
script: true
